#! /usr/bin/python3

import boto3
import passwords
import json
import sys
import cgitb
import os
import MySQLdb
import cgi

cgitb.enable()

conn = MySQLdb.connect(host=passwords.SQL_HOST, user=passwords.SQL_USER, passwd=passwords.SQL_PASS, db="servers")
cursor = conn.cursor()

form = cgi.FieldStorage()

def main():
    if os.environ["REQUEST_METHOD"] == "GET":
        add_server()

def add_server():

    if "user" in form:
        user = form["user"].value
    else:
        code_400()
        return
    if "desc" in form:
        desc = form["desc"].value
    else:
        desc = None

    ec2_r = boto3.resource( "ec2", region_name='us-east-1')

    with open("config_instance", "r") as file:
        config_contents = file.read()

    new_node = ec2_r.create_instances(
        ImageId='ami-01cc34ab2709337aa',
        InstanceType='t2.small',
        MinCount=1,
        MaxCount=1,
        KeyName='vockey',
        SecurityGroupIds=['sg-0ef8fe60744ffda0a'],
        UserData=config_contents
    )

    
    command = "INSERT INTO server (owner, description, instance, ready) VALUES(%s, %s, %s, %s)"
    values = (user, desc, new_node[0].instance_id, 0) #ready is 0 because server is not up
    cursor.execute(command, values)
    conn.commit()
    conn.close()
    code_303()
    os.system("/home/ec2-user/monitor_new_node %s %s 1>/home/ec2-user/log 2>/home/ec2-user/log &" %(new_node[0].instance_id, new_node[0].private_ip_address))



def code_404():
    print("Status: 404 Not Found")
    print()

def code_303():
    print("Status: 303 Redirect")
    print("Location: ", os.environ["REQUEST_URI"])
    print()

def code_400():
    print("Status: 400 Bad Request")
    print()

main()
