#! /usr/bin/python3

import passwords
import json
import sys
import os
import MySQLdb

conn = MySQLdb.connect(host=passwords.SQL_HOST, user=passwords.SQL_USER, passwd=passwords.SQL_PASS, db="servers")
cursor = conn.cursor()

instance_id = sys.argv[1]
private_ip = sys.argv[2]

cursor.execute("SELECT * FROM server")
data = cursor.fetchall()
conn.commit()
key = 0
for i in data:
    if i[3] == instance_id:
        key = i[0]

cursor.execute("UPDATE server SET ready=1 WHERE id=%s" %(key))
conn.commit()
conn.close()
